# Generated by Django 4.0.2 on 2022-02-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('language', models.CharField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('CHI', 'Chinese'), ('FRA', 'French'), ('GER', 'German'), ('HIN', 'Hindi'), ('JPN', 'Japanese'), ('AR', 'Arabic')], max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('EUR', 'Euro'), ('GBP', 'Pound')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='newpoly', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('polygon', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozioApp.provider')),
            ],
        ),
    ]
