# Generated by Django 3.2.12 on 2022-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozioApp', '0002_alter_provider_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('GBP', 'Pound'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('CHI', 'Chinese'), ('FRA', 'French'), ('GER', 'German'), ('JPN', 'Japanese')], max_length=3),
        ),
    ]
